swagger: "2.0"
info:
  version: "0.0.1"
  title: Attestation of housing facts
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: Returns all page data
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Page"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /events:
    get:
      description: Returns all events
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventsOverview"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /properties:
    get:
      description: Returns all properties
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PropertiesOverview"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profile:
    get:
      description: Returns user profile
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Page:
    required:
      - message
    properties:
      message:
        type: string
      profile:
        $ref: "#/definitions/User"
      properties:
        type: array
        items:
          $ref: "#/definitions/Property"
      events:
        type: array
        items:
          $ref: "#/definitions/Event"
  PropertiesOverview:
    required:
      - message
    properties:
      properties:
        type: array
        items:
          $ref: "#/definitions/Owner"
  Property:
    required:
      - message
    properties:
      id:
        type: number
      message:
        type: string
      name:
        type: string
      owner:
        $ref: "#/definitions/Owner"
      address:
        type: string
      sqFt:
        type: string
      insuranceCompany:
        type: string
      cadastre:
        type: string
  Owner:
    required:
      - message
    properties:
      message:
        type: string
  EventsOverview:
    required:
      - message
    properties:
      message:
        type: string
      description:
        type: string
      events:
        type: array
        items:
          $ref: "#/definitions/Event"
  Event:
    allOf:
      - $ref: '#/definitions/EventSummary'
      - $ref: '#/definitions/Document'
      - $ref: '#/definitions/Insurance'
      - $ref: '#/definitions/Builder'
  EventSummary:
    required:
      - timestamp
    properties:
      timestamp:
        type: string
      property:
        $ref: "#/definitions/Property"
      type:
        type: string
        enum: ["document", "work", "insurance" ]
      ownerGroup:
        type: string
        enum: ["legal", "admin", "owner", "builder", "insurance" ]
  Document:
    properties:
      source:
        type: string # storage or CDN
      type:
        type: string
        enum:
          - cadastre
          - plan
          - pus
          - acte notarial
          - liste vendeurs
  Insurance:
    properties:
      key:
        type: string
      value:
        type: string
      type:
        type: string
        enum:
          - insurance
  Builder:
    properties:
      type:
        type: string
        enum:
          - default
          - foundation
          - roof
          - walls
          - plumbing
          - electric
          - carpet
      phone:
        type: string
      address:
        type: string
      insuranceCompany:
        type: string
      estimatedCost:
        type: string
  User:
    required:
      - message
    properties:
      message:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      role:
        type: string
        enum: ["legal", "admin", "owner", "builder", "insurance"]
      username:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
