swagger: "2.0"
info:
  version: "0.0.1"
  title: Attestation of housing facts
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: Returns all page data
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Page"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /events:
    get:
      description: Returns all events
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventsOverview"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profile:
    get:
      description: Returns user profile
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Page:
    required:
      - message
    properties:
      message:
        type: string
      profile:
        type: string
      properties:
        type: array
        items:
          $ref: "#/definitions/Property"
      events:
        type: array
        items:
          $ref: "#/definitions/Event"
  Property:
    required:
      - message
    properties:
      message:
        type: string
      owner:
        $ref: "#/definitions/Owner"
      address:
        type: string
      sqFt:
        type: string
      insuranceCompany:
        type: string
      cadastre:
        type: string
  Owner:
    required:
      - message
    properties:
      message:
        type: string
  EventsOverview:
    required:
      - message
    properties:
      message:
        type: string
      description:
        type: string
      events:
        type: array
        items:
          $ref: "#/definitions/Event"
  Event:
    required:
      - message
    properties:
      message:
        type: string
      property:
        $ref: "#/definitions/Property"
      ownerGroup:
        type: string
        enum: ["legal", "admin", "owner", "builder", "insurance" ]
      timestamp:
        type: string
  Cadastre:
    properties:
      source:
        type: string # storage or CDN
      type:
        type: string
        enum:
          - plan
          - pus
          - acte notarial
          - liste vendeurs
  User:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
