swagger: "2.0"
info:
  version: "0.0.1"
  title: Attestation of housing facts
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /events:
    get:
      description: Returns all events
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/EventsOverview"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /profile:
    get:
      description: Returns user profile
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  EventsOverview:
    required:
      - message
    properties:
      message:
        type: string
      description:
        type: string
      events:
        type: array
        items:
          $ref: "#/definitions/Event"
  Event:
    required:
      - message
    properties:
      message:
        type: string
      property:
        $ref: "#/definitions/Property"
      timestamp:
        type: string
  User:
    required:
      - message
    properties:
      message:
        type: string
  Property:
    required:
      - guid
    properties:
      guid:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
